export enum ErrorStatus {
	EMAIL_EXIST = 'EMAIL_EXIST',

	USERNAME_EXIST = 'USERNAME_EXIST',

	USER_NOT_EXIST = 'USER_NOT_EXIST',

	INVALID_PASSWORD = 'INVALID_PASSWORD',

	SESSION_NOT_PARAMS_ID = 'SESSION_NOT_PARAMS_ID',
	SESSION_CURRENT_REMOVE = 'SESSION_CURRENT_REMOVE',

	URL_EXIST = 'URL_EXIST',
	URL_NOT_EXIST = 'URL_NOT_EXIST',

	ALIAS_EXIST = 'ALIAS_EXIST',
	ALIAS_NOT_EXIST = 'ALIAS_NOT_EXIST',

	LINKS_NOT_FOUND = 'LINKS_NOT_FOUND',
}
